### ISSUE TITLE
DI в вашем примере не работает

### ISSUE THREAD

**Issue by Pavelyev** [Agaspher20/OwinDISample#1]
`None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'IdentityDISample.Controllers.HomeController' can be invoked with the available services and parameters: Cannot resolve parameter 'IdentityDISample.Models.ApplicationDbContext context' of constructor 'Void .ctor(IdentityDISample.Models.ApplicationDbContext)'.`

В приложение добавлен код:

```
private ApplicationDbContext _context;

public HomeController(ApplicationDbContext context)
{
    _context = context;
}
```

То есть DI не работает

Меняю 

```
builder.RegisterType<ApplicationDbContext>().As<DbContext>().InstancePerRequest();
```

на 

```
builder.RegisterType<ApplicationDbContext>().AsSelf().InstancePerRequest();
```

 и главная открывается без ошибок.

Вы, кажется, везде местами перепутали типы в RegisterType и As. RegisterType для абстракции, As для реализации.

**Comment by mikhail-naumenko** [comment]
Вы неправильно воспользовались Dependency Injection
Из следующей строчки

```
builder.RegisterType<ApplicationDbContext>().As<DbContext>().InstancePerRequest();
```

видно, что ApplicationDbContext зарегистрирован как DbContext.
Чтобы получить инстанс ApplicationDbContext вам надо инжектить в конструктор DbContext, т.е. код должен выглядеть так:

```
private DbContext _context;
public HomeController(DbContext context)
{
     _context = context;
}
```

Поскольку это пример правильной организации DI контейнера, то ошибки здесь нет.
Если вы хотите пользоваться имплементацией ApplicationDbContext, то можете сделать так, как сделали в своем примере.
